### ISSUE TITLE
Email Sent but no received email on Gmail !!!

### ISSUE THREAD

**Issue by placebocurejava** [playframework/play-mailer#100]
Hi,
Finally the Java app works and i can see message "email sent" but no received emails on INBOX! any idea ?

Here are the steps I followed in the attached file:

![sans titre](https://cloud.githubusercontent.com/assets/18368701/15925971/fbdcb7b8-2e28-11e6-921a-251f9249e142.png)

**Comment by Mogztter** [comment]
Hello @placebocurejava 

`play.mailer.mock` should be `false`

**Comment by placebocurejava** [comment]
Hi,

I did not like any more PLAY MAILER...lot of configuration etc...
this is what i did this morning with  ( commons-email.jar ) without adding all config in ( play.plugins + build.sbt + application.conf....etc )

and finally it works really fine :  
![ggg](https://cloud.githubusercontent.com/assets/18368701/15928333/ce35f628-2e35-11e6-954c-f66f3fdbd897.png)

Now my question is:
is that the fact of adding an external jar such as "commons-email.jar" and working with this jar well cause problems of performance?
thank you.

**Comment by Mogztter** [comment]
> is that the fact of adding an external jar such as "commons-email.jar" and working with this jar will cause problems of performance?

Not at all, `play-mailer` relies on `commons-email.jar` anyway :wink:

**Comment by placebocurejava** [comment]
Hi,

why did you closed this issue?  the problem still occurs even if i changed mock to false..

**Comment by gmethvin** [comment]
@placebocurejava This is a bug tracker for play-mailer, not a place to get help. The mailing list is a better place for that. For something to be a bug, we'd have to confirm you are configuring things properly and you're still getting an issue, and that the problem is not in another library.

**Comment by wsargent** [comment]
Hi all -- placebocurejava has been banned from playframework, as he was posting on the google group with stolen credentials. His comments have been removed. Please see https://groups.google.com/forum/#!topic/play-framework/5FCht0abCI4 for more information.
