### ISSUE TITLE
Possibility to attach Report ( HTML + it's own folder )

### ISSUE THREAD

**Issue by placebocurejava** [playframework/play-mailer#101]
Hi,

Is it possible to attach in SendMail a directory or a folder of an HTML file such as a Report JASPER ?
Well, I generate three kind of report : 1- PDF   2- XLS   3-HTML but HTML REPORT GENERATED needs it's own folder or direcotry which resemble images etc...

![sans titre](https://cloud.githubusercontent.com/assets/18368701/16307039/57eb3170-394f-11e6-990b-32d7314a4449.png)

Thank you in advance.

**Comment by Mogztter** [comment]
Hello @placebocurejava 

I don't think you can attach a directory but you can attach multiple files. Your best option here is to generate a single HTML file with embedded images.

This question is not related to play-mailer, I will close this issue. 
As mentioned by @gmethvin please use stackoverflow or the mailing list to ask questions.

Thanks

**Comment by placebocurejava** [comment]
Bonjour,

Je me permets de t'écrire en francais pourvu que je suis francais
également, Tu es la seule personne jusqu'au jour qui supprimer mes issues
lol
Bref, Je n'ai pas le choix car JASPER genere un rapport HTML accompagné
d'un folder et pas de solution concernant les embeded...

Cette fois ci j'espère bien que tu puisses me répondre je suis pleinement
bloqué sur ce topic :
au pire donnes moi juste des idées stp juste ne me demandes pas de revoir
la doc car elle est pourrie...

[image: Inline images 1]

**Comment by Mogztter** [comment]
Bonjour,

Ta question ne concerne pas le projet c'est la raison pour laquelle je ferme ce ticket. Tu auras plus de chance de trouver une solution sur le forum de Jasper Report ou en cherchant sur Stackoverflow :wink: 

Je pense qu'il faut que tu trouve une solution pour que Jasper Report génère un fichier HTML contenant les images. En faisant une rapide recherche sur Google j'ai trouvé cette question sur Stackoverflow: http://stackoverflow.com/questions/6942373/export-to-single-html-with-embedded-images-using-jasper-report

**Comment by mkurz** [comment]
Please keep conversations in english...

**Comment by placebocurejava** [comment]
Hi,

Guillaume => vivant tu ne me sers pas à grand chose ^^

Matthias,

Could you tell me please if you have in mind a project that can get Input
parameters from select/deselect page list ( Play java ) ?
Thank you in advance.

**Comment by Mogztter** [comment]
> vivant tu ne me sers pas à grand chose ^^

???

**Comment by placebocurejava** [comment]
Je veux dire par la que : je demanderai à github de te punir pour moi lol
Mec stp je suis bloqué pour recuperer des checkbox selectionné sur une page
liste = help pleaaaase
Le 26 juin 2016 18:13, "Guillaume Grossetie" <notifications@github.com> a
écrit :

**Comment by Mogztter** [comment]
Locking this conversation.
He just made a death threat about me in French despite the fact that I'm trying to help him! Please report him.

> Guillaume => vivant tu ne me sers pas à grand chose ^^

Guillaume => alive you are useless to me...

**Comment by gmethvin** [comment]
@Mogztter I've reported him to github
