### ISSUE TITLE
Release 5.0.0

### ISSUE THREAD

**Issue by tsuyoshizawa** [playframework/play-mailer#103]
Play 2.5 is already released as official.

play-mailer version is still 5.0.0-M1.
If there is not critical issue for Play 2.5, I hope play-mailer version will be 5.0.0.

**Comment by Mogztter** [comment]
I agree! :+1: 
@gmethvin are you allow to perform a release ?

**Comment by mkurz** [comment]
+1 for a release

**Comment by gmethvin** [comment]
Just released 5.0.0 from master.

**Comment by Mogztter** [comment]
Yay thanks \o/
