### ISSUE TITLE
In Play 2.5 , Injecting MailerClient give compilation error

### ISSUE THREAD

**Issue by maltiyadav** [playframework/play-mailer#105]
I am trying to inject MailerClient but  its give "not found: type MailerClient" error .

import javax.inject.{Inject, Singleton}
import org.apache.commons.mail.EmailAttachment
import play.api.libs.mailer._

@Singleton
class EmailUtils @Inject() (mailerClient: MailerClient)

**Comment by maltiyadav** [comment]
My bad . Solved the problem .

**Comment by Mogztter** [comment]
No worries.
What was the issue ? It can help others and/or improve the documentation.

Thanks
Guillaume

**Comment by maltiyadav** [comment]
I have  not clean the target folder after upgrading the version.
I upgraded pay mailer v2.4.1 to v5.0.0  , injected  MailerClient into class component  and run application . Its throw compilation error . 
After running activator clean compile. Its work fine .

**Comment by Mogztter** [comment]
Ok thanks for the explanation, have fun :wink:
