### ISSUE TITLE
Attaching Excel files

### ISSUE THREAD

**Issue by arcteixeira** [playframework/play-mailer#114]
When an Excel file is attached it is sent as .dat. I've tried using other file formats and they arrive correctly. Is there a special way to attach these files? Thanks

**Comment by Mogztter** [comment]
Not to my knowledge... that's a really weird bug! I don't understand why/how an `.xls` file would be processed differently by commons email.

Do you have a code sample to reproduce this issue ? Did you try to send another `.xls` file ?

**Comment by arcteixeira** [comment]
After lots of testing, I realized I was attaching the file without extension... Once I added the .xls everything worked fine. 

Thaks for your reply!

**Comment by Mogztter** [comment]
Glad it's working for you, thanks for the follow up :+1:
