### ISSUE TITLE
ReplyTo adding multiple values is not supported

### ISSUE THREAD

**Issue by avivshafir** [playframework/play-mailer#118]
Is there any reason the replyTo field allows only adding one value?

**Comment by marcospereira** [comment]
Hey @avivshafir, there is no special reason to have this limitation. Even the underlying lib (commons-email) has support to add multiple addresses in replyTo field.

Do you want to submit a pull request to improve this?

Thanks.

**Comment by avivshafir** [comment]
#119

**Comment by mkurz** [comment]
Fixed with #119
