### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by schmitch** [playframework/play-mailer#127]
@gmethvin , @Mogztter it would be great to make a release soon. Since I removed play as a direct dependency it shouldn't be a big issue.

**Comment by gmethvin** [comment]
Sure. We are planning on doing the 2.6.0 release soon, so when I do that I can update the play test dependency and release.

**Comment by schmitch** [comment]
well I think it would be great to at least have a RC of play-mailer before the play 2.6 release, especially since the new play-mailer will run on 2.5.x and 2.6.x

**Comment by gmethvin** [comment]
Okay, that's fair. I'll release a 2.6.0-RC1 first then.

**Comment by gmethvin** [comment]
meant to say 6.0.0-RC1

**Comment by gmethvin** [comment]
https://oss.sonatype.org/content/repositories/releases/com/typesafe/play/play-mailer_2.12/6.0.0-RC1/
