### ISSUE TITLE
How to send a mail using TLSv1.2

### ISSUE THREAD

**Issue by ogis-onishi** [playframework/play-mailer#134]
Hi, I want to send a mail using TLS v1.2 for some reasons. Could you help me know how to set it on my configuration.

I have read the Getting Started section on the README but there is no place to set it.
https://github.com/playframework/play-mailer#getting-started

FYI: In Java Mail, I just write the following code to specify tls protocol. I want to do the same with play-mailer.

```java
Properties props = System.getProperties();
props.put("mail.transport.protocol", "smtps");
props.put("mail.smtp.port", PORT); 
props.put("mail.smtp.auth", "true");
props.put("mail.smtp.starttls.enable", "true");
props.put("mail.smtp.starttls.required", "true");
props.put("mail.smtps.ssl.protocols", "TLSv1.2")  // <- TLSv1.2 is set here
Session session = Session.getDefaultInstance(props);
// write some code to send an email
```

**Comment by Mogztter** [comment]
Commons email is using the `System.getProperties()` to instantiate a new `Session`:

https://github.com/apache/commons-email/blob/5516c487a5d03df520480d47f5c5ae5a3b3341d4/src/main/java/org/apache/commons/mail/Email.java#L637

So you'll need to set the property `mail.transport.protocol` and `mail.smtps.ssl.protocols`:

```java
System.setProperty("mail.transport.protocol", "smtps");
System.setProperty("mail.smtps.ssl.protocols", "TLSv1.2");
```

The other properties can be configured using a configuration file.

**Comment by ogis-onishi** [comment]
thanks!

**Comment by jason-lo** [comment]
props.put("mail.smtps.ssl.protocols", "TLSv1.2") is wrong here.
It should be 
props.put("mail.smtp.ssl.protocols", "TLSv1.2")
