### ISSUE TITLE
How to send emails with ssl?

### ISSUE THREAD

**Issue by Spenhouet** [playframework/play-mailer#136]
I have set the `ssl` option to `true` or `yes` (I don't know if there is a difference between `yes` and `true` or `no` and `false`) but still the debug output says that ssl is false (`isSSL false`). This sounds wrong or is this correct?

Config: 

```
play { 
  mailer {
    host = "exchange.****.de"
    port = 443
    ssl = true
    tls = false
    tlsRequired = false
    user = "****"
    password = "****"
  }
}
```

Output:

```
[debug] play.mailer - DEBUG SMTP: trying to connect to host "exchange.****.de", port 443, isSSL false
[error] ErrorHandler - Exception message: Sending the email to the following server failed : exchange.****.de:443
```

**Comment by schmitch** [comment]
not a bug. ssl port is definitiv not 443. most likely you need tls = true and ssl = false. also the port is either 25, 465, 587 (but the settings, change depending on your server)

**Comment by Spenhouet** [comment]
@schmitch That was not my question / bug report. I'm using our own server with a custom port configuration.

The question is: Why it reports **isSSL false** although I have set **ssl = true**?
