### ISSUE TITLE
Issue with MailerClient

### ISSUE THREAD

**Issue by karimireddy** [playframework/play-mailer#137]
Hi,
When I'm trying to upgrade MailClient for Play Framework 2.5 from API which is deprecated. I've followed the documentation and created the required files and given entries in required files as per documentation. After everything is set, when I try to run my application I'm getting the following error on the browser network response tab. Help needed to resolve the following error. 

**Unable to create injector, see the following errors:**

**1) No implementation for play.libs.mailer.MailerClient was bound.
  while locating play.libs.mailer.MailerClient
    for parameter 1 at com.*****.*****.email.SMTPProvider.<init>(SMTPProvider.java:31)
  while locating com.*****.*****.email.SMTPProvider
    for parameter 1 at com.*****.*****.conf.EmailProviderGuiceProvider.<init>(EmailProviderGuiceProvider.java:23)
  at com.*****.*****.conf.AppModule.configure(AppModule.java:89)**

**1 error**

**Comment by schmitch** [comment]
This is not a bug. You might forgot to add `"com.typesafe.play" %% "play-mailer-guice" % "6.0.1"`.
Please use the mailing list for questions.

**Comment by karimireddy** [comment]
Hi,
Thanks for the update. I've added that dependency to the "build.sbt" file already. But Still, I'm getting the issue.

**Comment by schmitch** [comment]
Actually without a reproducer and a full stacktrace it's hard to debug/analyze.

**Comment by karimireddy** [comment]
please give me your email id I'll share you the entire stack trace and how I stuck with this. 
Thank You

**Comment by schmitch** [comment]
You can find it on my github profile. You can also just create a small reproduction project on github.

**Comment by karimireddy** [comment]
Yeah, got it and I'll do that and let you know. Thank You very much for the prompt response :)
