### ISSUE TITLE
addReplyTo seems not working at all

### ISSUE THREAD

**Issue by almothafar** [playframework/play-mailer#142]
I'm using postmark to send emails, while [postmarkapp ](https://postmarkapp.com) not allowing me to send "from" any email except the one that I verify, I'm using the one that I verify to `from` and adding the email of user that using the from in website as `replyTo`, the problem that I get email for in `receiver` mailbox BUT when I try to reply it, I get `replyTo` as the same address as the email in `from` field, and the address that I add to `reploTo` is not there in any case.

    Email email = new Email();
    email.setSubject("test subject");
    email.setFrom("receiver@example.com");
    email.addReplyTo("replyTo@example.com");
    email.addTo("receiver@example.com");
    email.setBodyHtml("This is the body");
    mailerClient.send(email);

What is the problem? is it a bug, or is there something configured wrongly?

I'm using the latest play and play-mailer versions:

```
  "com.typesafe.play" %% "play-mailer" % "6.0.1",
  "com.typesafe.play" %% "play-mailer-guice" % "6.0.1",
```
```
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.11")
```

**Comment by almothafar** [comment]
It seems postmark issue not play-mailer, sorry :)

**Comment by Mogztter** [comment]
@almothafar No worries, thanks for the follow-up.
