### ISSUE TITLE
Email sent goes to spam

### ISSUE THREAD

**Issue by sagargit2** [playframework/play-mailer#152]
I am using **play-mailer 2.4.0** in my `play-scala` application. 
The email is sent but gmail detects it as spam everytime.

**Comment by mkurz** [comment]
This has absolutely nothing to do with `play-mailer`. As you said the E-Mail is sent. Therefore `play-mailer` did it's job.
You should read some guide on how to sent E-Mail reliable. Google for "[SPF](https://www.google.com/search?q=spf)", "[DKIM](https://www.google.com/search?q=DKIM)" and "[DMARC](https://www.google.com/search?q=DMARC)".

**Comment by vlasov01** [comment]
It will be great if play-mailer can add support for DKIM signing. There is a Java project that can be reused for signing for https://github.com/simple-java-mail/java-utils-mail-dkim .

**Comment by mkurz** [comment]
@vlasov01 That's definitely Interesting. A while ago I configured the exim MTA to DKIM sign outgoing e-mails, having that also in this library would be nice. I opened https://github.com/playframework/play-mailer/issues/242 - would you be keen to provide a pull request for that feature?
