### ISSUE TITLE
office365 smtp session

### ISSUE THREAD

**Issue by Ender-Wiggin** [playframework/play-mailer#156]
Hi there,

I'm having trouble with sending emails via office365. I've tried gmail and it works fine but this isn't working for some reason. Here's my config:

# Play mailer
play.mailer {
  host = "smtp.office365.com"
  port = 587
  tls = true
  user = "test@test.com"
  password = "test"
  props {
	starttls.enable = true
	starttls.required = true
  }
}

I get this error:
Sending the email to the following server failed : smtp.office365.com:587

Has anyone experienced anything similar?

Thanks!

**Comment by mkurz** [comment]
Can you provide more information about the error?
