### ISSUE TITLE
Release version 2.4.0 and 3.0.0-M1

### ISSUE THREAD

**Issue by Mogztter** [playframework/play-mailer#16]
@jroper Since we are breaking the API, I think it would be great to release version 2.3.6 to mark that change and update the README accordingly.

**Comment by Mogztter** [comment]
@jroper Hi, can we proceed with the release of `3.0.0-M1` and `2.4.0` ? 
In meantime I updated the README to avoid confusion.

**Comment by jroper** [comment]
Done, pending central sync.

**Comment by Mogztter** [comment]
Thanks!
