### ISSUE TITLE
.addTo() needs to be properly escaped or UTF-8 encoded

### ISSUE THREAD

**Issue by cejkajirka** [playframework/play-mailer#173]
When try something like this

`Email email = new Email().addTo("YOU, YOU ONLY YOU <email@example.com>");`

there is a complain:

> [EmailException: javax.mail.internet.AddressException: Illegal address in string ``YOU, YOU AND YOU <email@example.com>'']

**Comment by mkurz** [comment]
This is not a bug in `play-mailer`.
If you use a comma in the name part of the email you need to escape it. That how specs define an email address. Solution is:
```java
Email email = new Email().addTo("\"YOU, YOU ONLY YOU\" <email@example.com>");
```java
