### ISSUE TITLE
NTLM authentication

### ISSUE THREAD

**Issue by scand1sk** [playframework/play-mailer#176]
Hi,

It may not be an issue with Play-Mailer itself but rather the underlying JavaMail API, but I have trouble trying to connect to an MS Exchange SMTP server. I am connecting using plaintext SMTP on port 25. Apparently, the server only supports NTML authentication. EHLO on Telnet responds :
```
250-SIZE 37748736
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 XRDST
```

I carefully checked login and password are correct but still get `javax.mail.AuthenticationFailedException: 535 5.7.3 Authentication unsuccessful` in the logs. I do not know how to get more detail about what caused the authentication to fail (debug mode is set on both un play.mailer configuration and in logback.xml), but I suspect NTLM to be the issue. I am not the admin of the SMTP server and cannot reconfigure it.

Any thought ?

**Comment by mkurz** [comment]
I don't think this has something to do with play-mail. What you can do is: Set up a small java project which only uses the Apache commons-email library and try to send an email with it. If that works, lets see what we need to change in play-mailer to make this work.

**Comment by mkurz** [comment]
Closing this 3 year old issue, seems not related to play-mailer but a config problem.

@scand1sk Feel free to comment if you still think this is related to play-mailer.
