### ISSUE TITLE
Streaming attachments

### ISSUE THREAD

**Issue by tg44** [playframework/play-mailer#192]
Is there a way to stream the attachments instead of keeping the whole thing in memory? I have multiple files generated and added to the mails, they are `Source[ByteString, NotUsed]`s and I need to generate and wait all the data to get an `Array[Byte]` out of them, which is not really what I think optimal...

**Comment by mkurz** [comment]
With `play-mailers` own `Email` class, currently this is not possible (yet). Right now we support only [files or arrays](https://github.com/playframework/play-mailer/blob/8.0.1/play-mailer/src/main/scala/play/api/libs/mailer/Attachment.scala#L7-L22) as attachment.
However, `play-mailer` uses Apache Commons Email under the hood, which provides [some additional methods](https://commons.apache.org/proper/commons-email/javadocs/api-release/org/apache/commons/mail/MultiPartEmail.html#method.summary) to `attach(...)` attachments, like passing a `javax.activation.DataSource`...
You are welcome to provide a pull request... You would need to add another method to handle a `Source[ByteString, NotUsed]` and convert it to a `DataSource`, similarly to [these methods](https://github.com/playframework/play-mailer/blob/86ddb28cca6c976ad81c9883b5db6c6e63fa1a91/play-mailer/src/main/scala/play/api/libs/mailer/CommonsMailer.scala#L126-L160).

Actually looking at the code it looks like there is a workaound for now... The `MailerClient` you inject is an object of `CommonsMailer`, therefore you could use the the ´[createEmail(...) method](https://github.com/playframework/play-mailer/blob/8.0.1/play-mailer/src/main/scala/play/api/libs/mailer/CommonsMailer.scala#L29) which gives you a Apache Commons `MultiPartEmail` which you can [then send](https://github.com/playframework/play-mailer/blob/86ddb28cca6c976ad81c9883b5db6c6e63fa1a91/play-mailer/src/main/scala/play/api/libs/mailer/CommonsMailer.scala#L21), like

```scala
val multipartEmail = commonsMailerClient.createEmail(myExistingEmail);
multipartEmail.attach(myDataSource, ...); // multipartEmail is Apaches own email implementation
....
commonsMailerClient.send(multipartEmail);
```

**Comment by tg44** [comment]
The project currently not use any akka deps, this was the main reason I didn't hop to a "lets make a PR" train.

What do you think, should we document this workaround, or create a module/artifact just for the additional streaming? Adding akka as a dep could be a pain, I would not cross that bridge if I don't need to...

**Comment by mkurz** [comment]
Finally found time for a PR: #193
