### ISSUE TITLE
[2.x] How to send a mail using TLSv1.2 or TLSv1.3

### ISSUE THREAD

**Issue by djonmayer** [playframework/play-mailer#194]
I have to use TLSv1.2 or TLSv1.3 with 2.4.1 of play-mailer-plugin.
In the new version of JDK TLSv1 and TLSv1.1 are disabled.
How I can configure play-mailer-plugin to use the new version of TLS?

**Comment by iammichiel** [comment]
HI @djonmayer 

Any success updating to work with TLS 1.2 or up?

**Comment by mkurz** [comment]
> In version 2.4.1 of mailer-plugin you can only use "smtp.xxx" for configuration.

v2.4.1 was released in 2015, you should upgrade. It is possible to use newer TLS versions, also see:
* https://github.com/playframework/play-mailer/issues/134
* https://github.com/playframework/play-mailer/issues/150

We are not going to fix v2.4.x anymore.
