### ISSUE TITLE
How is someone that is not (yet) fully Play/Scala/SBT literate supposed to tell what the actual version number is?

### ISSUE THREAD

**Issue by techmag** [playframework/play-mailer#26]
I've tried 

```
sbt.ResolveException: unresolved dependency: com.typesafe.play#play-mailer;2.4.0-RC1: not found
sbt.ResolveException: unresolved dependency: com.typesafe.play#play-mailer;2.4.0: not found
sbt.ResolveException: unresolved dependency: com.typesafe.play#play-mailer;2.4.1: not found
sbt.ResolveException: unresolved dependency: com.typesafe.play#play-mailer;2.4.1-SNAPSHOT: not found
sbt.ResolveException: unresolved dependency: com.typesafe.play#play-mailer;3.0.0-M1: not found
```
```
sbt.ResolveException: unresolved dependency: com.typesafe.play#play-mailer;{version}: not found 
```
(just in case this was supposed to be an automatic thingy...) 

There must be some "obvious" way to determine exactly what the current version is to the initiated. 

Please initiate me :) 

I fell in love with Play -- turns out that I'm really starting to hate sbt :(

**Comment by Mogztter** [comment]
Hi @techmag,

Could you copy and paste the content of your `build.sbt` ?

**Comment by techmag** [comment]
build.st

=======================
name := """TechnicalMagicWeb2"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.1"

libraryDependencies ++= Seq(
  jdbc,
  anorm,
  cache,
  ws
)
=======================

**Comment by Mogztter** [comment]
And where do you define the dependency on `com.typesafe.play#play-mailer` ?

**Comment by techmag** [comment]
OK - Now I have the following in build.st and it appears to work (Activator loads without complaint) -- need and end to end test where email actually goes out before I have full confirmation however. Currently have an elephant in the queue so it might be a few days before I get around to that. 

import com.github.play2war.plugin._

name := """AlphaICRM"""

version := "0.9-SNAPSHOT"

Play2WarPlugin.play2WarSettings

Play2WarKeys.servletVersion := "3.1"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.1"

libraryDependencies ++= Seq(
  "com.typesafe.play" %% "play-mailer" % "2.4.0",
  jdbc,
  anorm,
  cache,
  ws
)

It seems that I also now know about a resource (http://search.maven.org) where I can confirm existence of a Group (com.typesafe.play) and an ArtifactID (play-mailer_2.11) with a simple search. 

I realize this is basic knowledge for those literate in Play/Scala/SBT but could I suggest it is nonetheless in the basic docs (Readme.MD) for the benefit of future code-tourists like myself?

Thank you or taking the time to enlighten me by answering the question! Much appreciated.

**Comment by Mogztter** [comment]
> Thank you or taking the time to enlighten me by answering the question! Much appreciated.

You're welcome! I hope that you'll find the play-mailer useful :smile: 

> I realize this is basic knowledge for those literate in Play/Scala/SBT but could I suggest it is nonetheless in the basic docs (Readme.MD) for the benefit of future code-tourists like myself?

Yes indeed, we tried to keep the README concise but I'm sure we can improve it. Maybe we can add a link to the `sample/build.sbt` to explain how to add the dependency in a Play! project ? And explicitly say that the artifacts are published in Maven central with a link on (http://search.maven.org) ? Wdyt ?

**Comment by prashantkrv** [comment]
How to make the scala-play-mailer work with scala version 2.12.7 . It says the dependency  net.kaliber#scala-mailer-play_2.12;6.0.1: not found. How could I make this work? Its Urgent!
