### ISSUE TITLE
Switch to Jakarta Mail

### ISSUE THREAD

**Issue by mkurz** [playframework/play-mailer#261]
Just a reminder to switch from `javax.mail.*` to `jakarta.mail.*` and from `javax.activation.*` to `jakarta.activation.*` when possible.
This depends on commons-email however:
* https://github.com/apache/commons-email/pull/133
* https://github.com/apache/commons-email/pull/43
* https://github.com/apache/commons-email/pull/37

Probably [Angus Mail](https://github.com/eclipse-ee4j/angus-mail/tree/1.0.0) will be used as implemention of [Jakarta Mail 2.x](https://jakarta.ee/specifications/mail/).

(BTW: Also check [this line](https://github.com/playframework/play-grpc/blob/fc74fe1f673b0bc50c23c6220b09a65b96e75ee7/project/Dependencies.scala#L49) in play-grpc, not sure if or when we should change that exclude.)

**Comment by mkurz** [comment]
Apache Commons Email  2.0.0-M1 released:
- https://lists.apache.org/thread/hhj6ls084031h1b9l1knvhomyzbms4jt
  - https://lists.apache.org/thread/4m1p5zohdz5zq8vb9lnmb923zj6lmt43
  - https://lists.apache.org/thread/4m1p5zohdz5zq8vb9lnmb923zj6lmt43

Be aware that the groupid changed to `commons-email2-*`: https://repo1.maven.org/maven2/org/apache/commons/

**Comment by mikesname** [comment]
Upvoting this because I've just run into an incompatibility with Play Mailer and the Jakarta-based SMTP appender for the version of Logback used in Play 2.9. :frowning_man:

**Comment by mikesname** [comment]
@mkurz I've put in a PR with the upgraded deps. I've tested locally and all seems good, but let me know what else needs doing for an M1 release. I'm not even sure what the new versions would be given that 9.x and 10.x are current for Play 2.9 and 3.0 respectively - 11.x and 12.x?. Thanks!

**Comment by mikesname** [comment]
@mkurz thanks very much for this. I can't claim to have tested every aspect of functionality yet but works well for my purposes on Play 2.9.5.

**Comment by mkurz** [comment]
@mikesname Can you please also report overt at https://github.com/apache/commons-email/pull/43 to let the commons-mail maintainer know? So we get a RC and/or final release faster, thanks!
