### ISSUE TITLE
Bug encoding in setFrom()

### ISSUE THREAD

**Issue by devpad** [playframework/play-mailer#27]
Mistake in a name of the sender when using cyrillics

```java
Email email = new Email();
email.setFrom("Тест <test@example.com>");
```
Output:
```From: ""5AB" <test@example.com>```

Should be so:
```From: =?UTF-8?B?0KLQtdGB0YI=?= <test@example.com>```

**Comment by Mogztter** [comment]
Hello @devpad, can I ask you where the output came from ? I guess it's from the [mock implementation](https://github.com/playframework/play-mailer/blob/master/src/main/scala/play/api/libs/mailer/MailerPlugin.scala#L149)  but I want to be sure.

Thanks,
Guillaume.

**Comment by devpad** [comment]
Hello @Mogztter, yes, the original letter in Gmail, shows the same output.

**Comment by Mogztter** [comment]
Ok I will do some testing on this issue, thanks.

**Comment by Mogztter** [comment]
@devpad is your source code encoded in UTF-8 ?

**Comment by devpad** [comment]
@Mogztter, yes, source codes in UTF-8. The setFrom() method doesn't code a user name in UTF-8 whereas in the addTo() method everything works correctly.

Example:
```java
Email email = new Email();
email.setSubject("Example");
email.setFrom("Кириллица <login@gmail.com>");
email.addTo("Кириллица <login2@gmail.com>");
...
MailerPlugin.send(email);
```

Output in gmail:
```
...
Date: Sun, 15 Feb 2015 16:38:48 +0300 (MSK)
From: "8@8;;8F0" <login@gmail.com>
To: =?UTF-8?B?0JrQuNGA0LjQu9C70LjRhtCw?= <login2@gmail.com>
Message-ID: <.....>
Subject: Example
MIME-Version: 1.0
...
```

**Comment by Mogztter** [comment]
Strange... the play-mailer extension is based on Apache commons email and the code is similar between `setFrom` and `addTo`: 

 * setFrom() : http://commons.apache.org/proper/commons-email/apidocs/src-html/org/apache/commons/mail/Email.html#line.746
 * addTo : http://commons.apache.org/proper/commons-email/apidocs/src-html/org/apache/commons/mail/Email.html#line.767

You are using the plugin in Java but we simply convert the Java object Email to the Scala object Email : https://github.com/playframework/play-mailer/blob/master/src/main/scala/play/api/libs/mailer/MailerPlugin.scala#L114

Can you try to force the charset with `setCharset` (I don't see why this should fix this issue but who knows :smile: 
https://github.com/playframework/play-mailer/blob/master/src/main/scala/play/libs/mailer/Email.java#L136
