### ISSUE TITLE
publish 9.0.0-M2

### ISSUE THREAD

**Issue by ornicar** [playframework/play-mailer#273]
so we can upgrade our projects using play-mailer to scala 3.3.0! :)

**Comment by mkurz** [comment]
Done, I pushed 9.0.0-M2: https://github.com/playframework/play-mailer/releases/tag/9.0.0-M2
Usually this starts the publish job, however it seems GitHub is having issues with GitHub actions currently: https://www.githubstatus.com/
I will check back later.

**Comment by mkurz** [comment]
It worked now, should be available on Maven Central within the next 30 minutes I guess: https://github.com/playframework/play-mailer/actions/runs/5203165981/jobs/9385655065

**Comment by ornicar** [comment]
Awesome, thank you!
