### ISSUE TITLE
Release with bugfixes.

### ISSUE THREAD

**Issue by F0REacH** [playframework/play-mailer#33]
Hi. Can you make 2.4.1 or 2.4.1-SNAPSHOT release. I need issues from this commit : 3ae39a8d55ea26def38253cac8d4298ca703f03c
to be fixed pretty bad.
Thanks

**Comment by Mogztter** [comment]
Hi @F0REacH, yes sure, I can backport the commit and then ask @jroper to do the release.
If you want you can do the backport yourself (using cherry-pick).

**Comment by F0REacH** [comment]
Thanks. I'm not so familiar with git infrastructure and maybe there are some other commits which need to be included. So you guys can do better then me. I just reminded you about this issue and I would be grateful if you make it when you have time.

**Comment by Mogztter** [comment]
I though the commit was on `play24` branch, no need to backport anything... @jroper could you make a 2.4.1 release please ?

**Comment by jroper** [comment]
@Mogztter done, pending central sync.

**Comment by F0REacH** [comment]
Nice :+1: Thank you
