### ISSUE TITLE
MailPlugin not found in 3.0.0-M1

### ISSUE THREAD

**Issue by scaryroy** [playframework/play-mailer#34]
I checked the contribution guidelines, and I still didnt know whether I should post this on the mailing list or here. But the 3.0.0-M1 is broken and not compatible with play2.4, as (I checked in the code) it does not have the MailPlugin object. Are you able to release a M2 as soon as you get the chance?

**Comment by Mogztter** [comment]
> I checked the contribution guidelines, and I still didnt know whether I should post this on the mailing list or here.

Opening an issue on GitHub is fine.

> But the 3.0.0-M1 is broken and not compatible with play2.4, as (I checked in the code) it does not have the MailPlugin object. Are you able to release a M2 as soon as you get the chance?

Are you using Play 2.4.0-RC1 ? @jroper made some changes to make the plugin compatible with RC1, see #35

**Comment by scaryroy** [comment]
It was my mistake,

For play2.4, you dont need to add 1500:play.api.libs.mailer.CommonsMailerPlugin into your conf/play.plugins
