### ISSUE TITLE
Support for cid

### ISSUE THREAD

**Issue by FrEaKmAn** [playframework/play-mailer#37]
I'm trying to generate an email with inline image. Based on my tests, it seems that there is no way to define cid (it's not included in generated mail) for an inline attachment. 

Can you please verify?

**Comment by Mogztter** [comment]
Hello @FrEaKmAn, could you please attach the code you are using ?
Another solution is to use an HTML body but INLINE images should work.

**Comment by FrEaKmAn** [comment]
val files = Set(AttachmentData("chart", Files.readAllBytes(chartFilePath), "image/jpeg", None, Some(EmailAttachment.INLINE)))

    val email = new Email(
      subject,
      from,
      recipients,
      bodyText = Some("email test"),
      bodyHtml = Some("<html><body><img src="cid:chart" width="500" /></body></html>"),
      attachments = files.toSeq
    )

I think I copied everything OK (not Scala guy). Image is included in the email. When I checked the source, I saw the following parameters.

    Content-Type: image/jpeg; name=chart
    Content-Transfer-Encoding: base64
    Content-Disposition: inline; filename=chart
    Content-Description: chart 

But should it also include Content-ID parameter?

**Comment by Mogztter** [comment]
I'm not familiar with Content-ID but I think that the inline attachment and the cid are two separated things in commons email.
Inline attachment are handled with the [attach()](https://commons.apache.org/proper/commons-email/apidocs/org/apache/commons/mail/MultiPartEmail.html#attach(java.net.URL, java.lang.String, java.lang.String, java.lang.String)) method. But to embed an image we should use the [embed()](https://commons.apache.org/proper/commons-email/apidocs/org/apache/commons/mail/HtmlEmail.html#embed(java.io.File, java.lang.String)) method.

One workaround is to encode your image in base64: 
```html
<img alt="char" src="data:image/jpeg;base64,/9j/4S/+RXhpZgAATU0AKgAAAAgACAESAAMAENkDZ5u8/61a+X.." />
```

Or host your image somewhere and use and URL to avoid increasing the size of your email.

**Comment by FrEaKmAn** [comment]
Yes, there is a nice example under **Sending HTML formatted email section** (https://commons.apache.org/proper/commons-email/userguide.html)

Using base64 is not an option. Similar for hosting the image.

CommonsMailer has everything already implemented, we just need to extend play-mailer.

**Comment by jroper** [comment]
On data images - a number of mail clients don't support data images, and many of the web based clients strip them out.

**Comment by FrEaKmAn** [comment]
Everything is nicely described in this blog post: https://sendgrid.com/blog/embedding-images-emails-facts/

@Mogztter I agree having an extra attribute should do the trick.

**Comment by jamesallchin** [comment]
:thumbsup:

I agree with @FrEaKmAn - this is really important. It's a necessity to embed images inline in the emails we are sending - base64 encoding is not an suitable alternative because it's not supported by Outlook (a major email client in Enterprises) 

Essentially this means that we can't use Play Mailer and will have to look at an alternative
