### ISSUE TITLE
cherry-pick changes before 3.0 release

### ISSUE THREAD

**Issue by mkurz** [playframework/play-mailer#38]
Following changes are not in the `play24` branch yet:
* #25
* #28
* "simplify sample" (https://github.com/playframework/play-mailer/commit/2c7656e09da6c1a88117f22537948fe5512f1b8f) (?)

Proposal: Rename current `master` branch to `2.3.x` and `play24` should become new `master` branch.

**Comment by Mogztter** [comment]
Done! :smile:
