### ISSUE TITLE
Having an issue building the master branch (JDK?)

### ISSUE THREAD

**Issue by duketon** [playframework/play-mailer#43]
When trying to compile `master` I get : 

```
sbt.ResolveException: unresolved dependency: org.json4s#json4s-native_2.10;3.2.10: configuration not found in org.json4s#json4s-native_2.10;3.2.10: 'master(compile)'. Missing configuration: 'compile'. It was required from net.databinder.dispatch#dispatch-json4s-native_2.10;0.11.2 compile
```

The `2.3.x` branch builds find. From what I can tell the only diff between the branches that would cause issues with building is the switch to v8 of the JDK. Which is strange since I'm running Java 8:

``` 
$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

```
 $ javac -version
javac 1.8.0_45
```

Any ideas? I'm probably missing something simple!
Thanks

**Comment by Mogztter** [comment]
I think your Scala version must be 2.11. What is your version of `sbt` or `activator` ? How do you build the project ? Can you give us the command line ?

Thanks

**Comment by duketon** [comment]
Sure,

```
$ scala -version
Scala code runner version 2.11.4 -- Copyright 2002-2013, LAMP/EPFL

$ sbt --version
sbt launcher version 0.13.7
```

Seems strange, not sure what else to try.

**Comment by Mogztter** [comment]
And what is the command you are running ? sbt compile ?
Le 19 mai 2015 11:05 AM, "Michael Kendra" <notifications@github.com> a
écrit :

**Comment by duketon** [comment]
Yes, `sbt compile`

**Comment by Mogztter** [comment]
I'm using `activator`:

```
activator clean compile
[info] Loading project definition from /home/guillaume/workspace/opensource/play-mailer/project
[info] Set current project to play-mailer (in build file:/home/guillaume/workspace/opensource/play-mailer/)
[success] Total time: 0 s, completed 19 mai 2015 19:43:53
[info] Updating {file:/home/guillaume/workspace/opensource/play-mailer/}play-mailer...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source and 4 Java sources to /home/guillaume/workspace/opensource/play-mailer/target/scala-2.10/classes...
[success] Total time: 6 s, completed 19 mai 2015 19:43:59
```

```
activator --version
sbt launcher version 0.13.8-M5
```

Maybe try to download the latest sbt version ?
Are you behind a proxy ? Because the dependency `org.json4s#json4s-native_2.10;3.2.10` is in the Maven repository : http://repo1.maven.org/maven2/org/json4s/json4s-native_2.10/3.2.10/

**Comment by duketon** [comment]
Got to the bottom of this.

I noticed I had some `org.json4s` packages in my `ivy2` local cache so I cleared them out and everything's fine now!
