### ISSUE TITLE
Release a new milestone for Play 2.4.0

### ISSUE THREAD

**Issue by Mogztter** [playframework/play-mailer#45]
I think we need to release a new milestone (M2) for Play 2.4.0 for Scala 2.10 and Scala 2.11. Maybe after https://github.com/playframework/play-mailer/pull/44 to avoid breaking changes.

**Comment by jroper** [comment]
I've just released 3.0.0-RC1.

**Comment by Mogztter** [comment]
Thanks!

**Comment by Mogztter** [comment]
Closed via https://github.com/playframework/play-mailer/commit/c5b54f60a1223bd5b864d78d7b0b4a4a1363a7d0
