### ISSUE TITLE
play.mailer configuration does not work

### ISSUE THREAD

**Issue by scesbron** [playframework/play-mailer#47]
I am using play-mailer 3.0.0-RC1 with play 2.4.0 java.

When I start my app I have a warning that tolds me to use the new syntax for configuration

But with this new syntax I have an exception `java.lang.RuntimeException: play.mailer.host needs to be set in application.conf in order to use this plugin (or set play.mailer.mock to true)`

Configuration that works

    smtp {
      host = "mailtrap.io"
      port = 2525
      tls = true
      user = "xxx"
      password = "xxx"
    }

Configuration that does not work

    play {
      mailer {
        host = "mailtrap.io"
        port = 2525
        tls = true
        user = "xxx"
        password = "xxx"
      }
    }

**Comment by Mogztter** [comment]
Hi @scesbron,

I think the root cause is that I added the deprecated configuration in `reference.conf` to avoid an exception but this is causing other issues... https://github.com/playframework/play-mailer/pull/44

Hopefully there's a `getDeprecatedWithFallback` method that seems to do the job :smile:

**Comment by Mogztter** [comment]
Could you test with master ?

**Comment by scesbron** [comment]
Sorry but I have always used standard dependencies : how can I test with master : do I have to fetch the repository and build it ? what kind of dependency do I declare in my project ?

**Comment by Mogztter** [comment]
Do you have `activator` installed ? If yes, it's easy:

```
$ git clone git@github.com:playframework/play-mailer.git
$ cd play-mailer
$ activator
> + publish-local
```

Then use the published version in your project:
```
"com.typesafe.play" %% "play-mailer" % "3.0.1-SNAPSHOT"
```

**Comment by scesbron** [comment]
Hi

It is ok with master

Thx

**Comment by Mogztter** [comment]
OK great we will release a new version soon :)
Le 3 juin 2015 8:45 AM, "Sebastien Cesbron" <notifications@github.com> a
écrit :

**Comment by jroper** [comment]
3.0.1 is released.

**Comment by Mogztter** [comment]
Thanks @jroper !
As a side note could you please remove the tag `v2.3.1` ? I deleted this tag and recreated a new one called `2.3.1` to stick with the naming convention. But when you release a new version this tag is pushed on GitHub.

**Comment by jroper** [comment]
Deleted locally and remotely.
