### ISSUE TITLE
Instantiation of a MailerClient

### ISSUE THREAD

**Issue by pejaham** [playframework/play-mailer#53]
I would like to instantiate an instance of a MailerClient outside of a Play controller or component (i.e. without dependency injection) for usage in a Util object, like:

object Util {
  val mailerClient = xxxxx
  def sendMail(email: Email) {
    mailer.send(email)
  }

Do I have to use native Guice or how does this work?

Thanks,
Peter

**Comment by jroper** [comment]
Hi @pejaham, questions like this are best asked on the Play mailing list, not the issue tracker.

You can instantiate a mailer client by going:

```scala
import play.api._
val configuration = Configuration.load(Environment.simple())
val mailerClient = new play.api.libs.mailer.CommonsMailer(configuration)
```
