### ISSUE TITLE
Test Play App with smtp.mock=true configuration param raises an error 

### ISSUE THREAD

**Issue by aBuder** [playframework/play-mailer#58]
I hav set in my application configuration the param smpt.mock=true and I get the following error by executing the testcae. What should be wrong?

java.lang.RuntimeException: smtp.host needs to be set in application.conf in order to use this plugin (or set smtp.mock to true)
```
smtp.mock=true
#smtp.host=smtp.gmail.com
#smtp.port=587
#smtp.ssl=true
#smtp.user="xxx"
#smtp.password=xxx
```
```
    @Test
    public void testIndexWithTestServerRunnable() {
        running(testServer(3333), new Runnable() {
            @Override
            public void run() {
                assertThat(
                        WS.url("http://localhost:3333").get().get(5000).getStatus()
                ).isEqualTo(OK);
            }
        });
    }
```

**Comment by Mogztter** [comment]
Hello @aBuder,
Can you show your controller code ? What version of the plugin do you use ?

**Comment by Mogztter** [comment]
@aBuder ping!

**Comment by Mogztter** [comment]
@aBuder pong ? :wink:

**Comment by Mogztter** [comment]
I'm closing this issue, please reopen if you still have a problem.
