### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by pycloux** [playframework/play-mailer#60]
Hi All,

The "configure" method is a real plus.
Please do you know when the change will be released ?

Regards,

PYC

**Comment by Mogztter** [comment]
Hi @pycloux,

There's a ["debate"](https://github.com/playframework/play-mailer/issues/51#issuecomment-121798831) to determine if this is the right way to implement this feature.
I'm not entirely satisfied by the mutable/side effect on the current implementation but in the other hand the API is easy to use... @jroper may have a better implementation but I'm still trying to understand how this is gonna work with the DI (and how to implement it in a backward compatible way).

If you have an idea, feel free to jump into the discussion :smile:
