### ISSUE TITLE
Provide a way to make the Logger in MockMailer overridable (DI)

### ISSUE THREAD

**Issue by schmitch** [playframework/play-mailer#76]
Hello, currently it would be great if we could change the Logger in MockMailer. Currently MockMailer could be used for testing, however thats impossible if the Mailer uses a static Logger instance.

It would help to make things like this work: http://stackoverflow.com/questions/17719552/unit-test-logger-messages-using-specs2-scalalogging

However at the moment there is no possible way to inject the Logger from Play!

**Comment by Mogztter** [comment]
Why did you close this issue ? Did you find a "workaround" ?

**Comment by schmitch** [comment]
No but I looked at the code and then I saw that's not as easy as I've thought and I need to find a way to support it.
