### ISSUE TITLE
Change the documentation format

### ISSUE THREAD

**Issue by schmitch** [playframework/play-mailer#87]
Currently the documentation format is in Ascii Doc I don't think that is suitable anymore.
I would like to propose a switch to either Markdown or RST

**Comment by Mogztter** [comment]
Could you argue why you think AsciiDoc is not suitable anymore ?

**Comment by schmitch** [comment]
Currently the problem with AsciiDoc are the following:

- less editor support
- currently we use bitbucket internally and asciidoc doesn't render there without a plugin
- less people are knowing ascii doc, especially not people here on github
- playframework uses markdown (https://github.com/playframework/playframework/tree/master/documentation/manual, https://github.com/playframework/anorm/tree/master/docs/manual/working/scalaGuide/main/sql) so I think this project is related so it should do the same

Something that doesn't count, personally I dislike the syntax but that is nothing subjective.

**Comment by mkurz** [comment]
Because playframework uses markdown I think we should use markdown here as well.

**Comment by mkurz** [comment]
Fixed in #126
