### ISSUE TITLE
Adding the user email to the HTML body doing bulk emails

### ISSUE THREAD

**Issue by luukjansen** [playframework/play-mailer#92]
A question: is it possible in a bulk email situation to add the target email to the html?

Google's guidelines suggest that there should be an unsubscribe link which only needs one click for the user to unsubscribe. This means that each email is unique. Currently I add all my recipients to a single message, but I don't see a way of doing this.

I haven't tested the impact of creating 5000+ separate emails, and that might be an option, but I would first like to check if there is a more efficient way.

**Comment by Mogztter** [comment]
Hello @luukjansen, I'm not an email expert but I don't think this is doable. If you scared about sending 5000+ emails you could use an email service provider (Sendgrid, Mandrill...). We have an issue to integrate play-mailer with email providers: https://github.com/playframework/play-mailer/issues/10

**Comment by mkurz** [comment]
> I haven't tested the impact of creating 5000+ separate emails, and that might be an option, but I would first like to check if there is a more efficient way.

You need to create separate emails, there is no other way round.

> Currently I add all my recipients to a single message

This is a bad idea, [GDPR](https://gdpr.eu/) wants to talk to you :wink:
