### ISSUE TITLE
com.typesafe.play#play-mailer_2.11;4.0.0-SNAPSHOT: not found

### ISSUE THREAD

**Issue by MuBoori** [playframework/play-mailer#93]
Hello,

I'm trying to use the newest version 4.0.0-SNAPSHOT but it is not in the Maven repo.
It says 
com.typesafe.play#play-mailer_2.11;4.0.0-SNAPSHOT: not found

**Comment by Mogztter** [comment]
Hi @MuBoori 

Did you try again recently ? Maybe the publishing process takes some time...

**Comment by MuBoori** [comment]
Still not working.
according to http://mvnrepository.com/artifact/com.typesafe.play/play-mailer_2.11
There is no version  4.0.0-SNAPSHOT.

Do I need to add different  resolver ?

**Comment by schmitch** [comment]
Actually you could easily see if it's already uploaded here:

    http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.typesafe.play%22%20AND%20a%3A%22play-mailer_2.11%22

**Comment by MuBoori** [comment]
@schmitch  you meant this version 4.0.0-M1. This does not work in play 2.5. I get method not found when I try to injection but it works in the old version 2.4.6 .

**Comment by schmitch** [comment]
@MuBoori actually I just wanted to say that when there is no 4.0.0-SNAPSHOOT on search.maven.org you can't probably resolve it ;)

**Comment by MuBoori** [comment]
@schmitch I tried to the build file [here](https://github.com/playframework/play-mailer/blob/master/samples/runtimeDI/build.sbt) hoping it will works with Play 2.5 but it did not work.

Sorry I'm a bit new in Play framework world.

**Comment by schmitch** [comment]
@MuBoori you've understood me wrong.
Actually Play uses sbt as his build too which resolves everything from the Maven Central Repository so the error

     com.typesafe.play#play-mailer_2.11;4.0.0-SNAPSHOT: not found

comes from the fact that there is no ``4.0.0-SNAPSHOT`` on the central repository.
This is the Link where you could see all version of play-mailer on the central repository: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.typesafe.play%22%20AND%20a%3A%22play-mailer_2.11%22

I think to use play-mailer for Play 2.5 you need to wait until somebody makes a release: #95 However I don't think it will take too long. So please be patient.

**Comment by MuBoori** [comment]
@schmitch yeah, I realised it won't work because there is no  4.0.0-SNAPSHOT in repo. so anyway, I resolved my issue by using https://commons.apache.org/proper/commons-email/ java library.

**Comment by Mogztter** [comment]
@MuBoori version 5.0.0-M1 has been released, you can now use this version with Play 2.5 or 4.0.0-M1 with Play 2.4.
