### ISSUE TITLE
Publish version 4.0.0 "final" version

### ISSUE THREAD

**Issue by Mogztter** [playframework/play-mailer#94]
I think we should publish a version 4.0.0 "final" version for Play! 2.4 (with commons-email 1.4) from this commit: https://github.com/playframework/play-mailer/commit/4371da092d1f30ae7334ba8f26394b15e2da6545

**Comment by schmitch** [comment]
What about 9d3da9f57696f32031a5cf16e415bd85fed76c87?

**Comment by Mogztter** [comment]
@schmitch Since we are introducing breaking changes, I think it's better to leave this change for 5.0.0.M1 (see #95). Wdyt ?

**Comment by schmitch** [comment]
yeah that's true.

**Comment by gmethvin** [comment]
@Mogztter You should probably create a 4.x branch so we can release from there.

**Comment by Mogztter** [comment]
@gmethvin yes you're absolutely right, I will do it in the next few days

**Comment by Mogztter** [comment]
Done!
@gmethvin could you please release version `4.0.0` from 4.x branch ?

**Comment by gmethvin** [comment]
https://repo1.maven.org/maven2/com/typesafe/play/play-mailer_2.11/4.0.0/

**Comment by Mogztter** [comment]
Awesome, thanks!
