### ISSUE TITLE
Publish version 5.0.0.M1 version

### ISSUE THREAD

**Issue by Mogztter** [playframework/play-mailer#95]
This version will be compatible with Play! 2.5 and will make it easier to use dynamic configuration with runtime DI: https://github.com/playframework/play-mailer/pull/81

This version must be released from `master` branch.

**Comment by lisinge** [comment]
Would be great if we could have this release so that we can push it to environments which rely on it being on the central repository

**Comment by Mogztter** [comment]
@jroper Would you have time to do a release ?

**Comment by kay-es** [comment]
release would be great! updated to 2.5 and need the playmailer :s

**Comment by oexza** [comment]
ping! @jroper

**Comment by lisinge** [comment]
Isn't there anyone else on the Play team that can push a release if @jroper is busy?

**Comment by mkurz** [comment]
@jroper @gmethvin @richdougherty Maybe it would be good to give @Mogztter the permissions to release new versions on this repo?

**Comment by franzgranlund** [comment]
So there is no working mailer for 2.5 at the moment? :-/

**Comment by Mogztter** [comment]
@franzgranlund You're right, the latest released version (4.0.0-M1) is not compatible with Play 2.5 because we are using `config.getOptional` instead of `config.get[Option]`: https://github.com/playframework/play-mailer/commit/575968e60ff99e1a3472ba184fc286102bc2d8cb#diff-a1708174875ec5c58582d97ce301e053R321

Since we don't publish SNAPSHOT, the only alternative is to build play-mailer from source.

> Isn't there anyone else on the Play team that can push a release if @jroper is busy?

I don't know :confused: 
> @jroper @gmethvin @richdougherty Maybe it would be good to give @Mogztter the permissions to release new versions on this repo?

Good idea, I vote for myself :wink:

**Comment by lisinge** [comment]
Yeah it feels like there needs to be at least one more person who can create a release. It's kind of a showstopper for a lot of people right now who wants to update to play 2.5.

**Comment by gmethvin** [comment]
I just published 5.0.0-M1. I can do releases now and you could also probably ask @wsargent if I'm not around.

**Comment by Mogztter** [comment]
Thanks @gmethvin !

**Comment by lisinge** [comment]
Thanks!
