### ISSUE TITLE
how to  set password runtime

### ISSUE THREAD

**Issue by deter2003** [playframework/play-mailer#99]
how to change password runtime? don not configure in application.conf, eg.read from DB.

**Comment by Mogztter** [comment]
Hello,

Are you using Java or Scala ? with runtime DI or compile time DI ?

You can create a custom provider or instantiate a new SMTPConfiguration. See https://github.com/playframework/play-mailer/blob/master/user-manual.adoc

**Comment by Mogztter** [comment]
ping @deter2003 ?

**Comment by Mogztter** [comment]
Does my reply answer your question @deter2003 ? Can I close this issue/question ?

**Comment by azwar** [comment]
@deter2003  You can just simply pass it when starting activator:

on development mode `activator -Dplay.mailer.password="yourpassword"`
on production `yourappname/bin/appname -Dplay.mailer.password="yourpassword"`
